//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Reflection;
        ///
        ////// &lt;summary&gt;
        ////// 这个文件属于dbormCompiler项目的资源文件，
        ////// 在扩展修改后，需要重新把此文件拖放到dbormCompiler -&gt; Properties -&gt; Resources.resx 的资源文件中
        ////// 替换旧的同名文件，同时重新编译dbormCompiler项目生成新的dbormCompiler.dll
        ////// &lt;/summary&gt;
        ///
        ///namespace DataBaseOp
        ///{
        ///
        ///    public class DataBaseAccess&lt;T&gt;
        ///    {
        ///        public SqlConnection con;
        ///        public SqlTransaction trans;
        ///        public  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DataBaseAccess {
            get {
                return ResourceManager.GetString("DataBaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ////// &lt;summary&gt;
        ////// 这个文件属于dbormCompiler项目的资源文件，
        ////// 在扩展修改后，需要重新把此文件拖放到dbormCompiler -&gt; Properties -&gt; Resources.resx 的资源文件中
        ////// 替换旧的同名文件，同时重新编译dbormCompiler项目生成新的dbormCompiler.dll
        ////// &lt;/summary&gt;
        ////// 
        ///namespace DbInfoCreate
        ///{
        ///    
        ///    public class DbToCSharpInfo
        ///    {
        ///        public s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DbCreate {
            get {
                return ResourceManager.GetString("DbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System.Data.SqlClient;
        ///using System;
        ///using System.Data;
        ///using System.Threading;
        ///
        ////// &lt;summary&gt;
        ////// 这个文件属于dbormCompiler项目的资源文件，
        ////// 在扩展修改后，需要重新把此文件拖放到dbormCompiler -&gt; Properties -&gt; Resources.resx 的资源文件中
        ////// 替换旧的同名文件，同时重新编译dbormCompiler项目生成新的dbormCompiler.dll
        ////// &lt;/summary&gt;
        ////// 
        ///namespace DataBaseOp
        ///{
        ///    public class ScDataBaseTableOpBase : IDisposable
        ///    {
        ///        public string dbName;
        ///        public string conStr;
        ///        public SqlConnection con;
        ///
        ///        SqlHelper sqlHelper = ne [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ScDataBaseTableOpBase {
            get {
                return ResourceManager.GetString("ScDataBaseTableOpBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///
        ////// &lt;summary&gt;
        ////// 这个文件属于dbormCompiler项目的资源文件，
        ////// 在扩展修改后，需要重新把此文件拖放到dbormCompiler -&gt; Properties -&gt; Resources.resx 的资源文件中
        ////// 替换旧的同名文件，同时重新编译dbormCompiler项目生成新的dbormCompiler.dll
        ////// &lt;/summary&gt;
        ////// 
        ///namespace DataBaseOp
        ///{
        ///    public class SqlHelper
        ///    {
        ///        public SqlHelper()
        ///        {
        ///        }
        ///        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlHelper {
            get {
                return ResourceManager.GetString("SqlHelper", resourceCulture);
            }
        }
    }
}
